name: basic
description: A basic game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.0.0
  go_router: ^14.0.0
  logging: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  auto_size_text: ^3.0.0
  simple_fsm: ^0.2.0+2
  async: ^2.11.0
  sensors_plus: ^6.1.1
  stop_watch_timer: ^3.2.1
  vibration: ^2.0.1
  wakelock_plus: ^1.2.10

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sfx/
    - assets/words/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_gen:
  output: lib/generated/
